theme: jekyll-theme-slate
title: Chinese Trade Data 2000-2010
description: This program proposes to normalise the Chinese Trade Data in a very simple way. The final table is stored in Google Big Query, ready to work with!
